CREATE DATABASE `clientes` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `clientes`;

-- MySQL Script generated by MySQL Workbench
-- dom 23 oct 2022 18:29:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clientes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clientes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clientes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `clientes` ;

-- -----------------------------------------------------
-- Table `clientes`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes`.`persona` (
  `idpersona` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `edad` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clientes`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(45) NOT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  `persona_idpersona` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcliente`, `persona_idpersona`),
  INDEX `fk_cliente_persona1_idx` (`persona_idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `clientes`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clientes`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes`.`cuenta` (
  `idcuenta` INT NOT NULL AUTO_INCREMENT,
  `tipo_cuenta` VARCHAR(45) NOT NULL,
  `saldo_inicial` BIGINT NOT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idcuenta`),
  INDEX `fk_cuenta_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cuenta_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `clientes`.`cliente` (`idcliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clientes`.`movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes`.`movimientos` (
  `idmovimientos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tipo_movimiento` VARCHAR(45) NOT NULL,
  `valor` BIGINT NOT NULL,
  `saldo` BIGINT NOT NULL,
  `cuenta_idcuenta` INT NOT NULL,
  PRIMARY KEY (`idmovimientos`),
  INDEX `fk_movimientos_cuenta1_idx` (`cuenta_idcuenta` ASC) VISIBLE,
  CONSTRAINT `fk_movimientos_cuenta1`
    FOREIGN KEY (`cuenta_idcuenta`)
    REFERENCES `clientes`.`cuenta` (`idcuenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
